'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class dt_hard
    Public Property Id As Integer
    Public Property hard As String
    Public Property user_id As Integer
    Public Property position_id As Integer
    Public Property comment As String

    Public Overridable Property dt_position As dt_position
    Public Overridable Property dt_user As dt_user

End Class
