'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはテンプレートから生成されました。
'
'     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
'     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class db_SystemEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=db_SystemEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property dt_hard() As DbSet(Of dt_hard)
    Public Overridable Property dt_position() As DbSet(Of dt_position)
    Public Overridable Property dt_user() As DbSet(Of dt_user)

End Class
